# Generated by Django 5.1.7 on 2025-03-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quests", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievement",
            name="condition_type",
            field=models.CharField(
                choices=[
                    ("quest_complete_count", "퀘스트 완료 횟수"),
                    ("level_reach", "레벨 도달"),
                    ("reward_buy_count", "보상 구매 횟수"),
                    ("coin_collect", "보유 코인 수"),
                    ("daily_quest_count", "일일 퀘스트 완료 누적 수"),
                    ("weekly_quest_count", "주간 퀘스트 완료 누적 수"),
                    ("consecutive_days", "연속으로 퀘스트를 완료한 날 수"),
                ],
                max_length=30,
            ),
        ),
    ]
